SELECT S.NAME, G.GRADE, S.MARKS
FROM STUDENTS S, GRADES G
WHERE G.GRADE >=8 AND S.MARKS BETWEEN G.MIN_MARK AND G.MAX_MARK
ORDER BY G.GRADE DESC, S.NAME;
SELECT NULL, G.GRADE, S.MARKS
FROM STUDENTS S, GRADES G
WHERE G.GRADE <8 AND S.MARKS BETWEEN G.MIN_MARK AND G.MAX_MARK
ORDER BY G.GRADE DESC, S.MARKS;
