SELECT H.HACKER_ID , H.NAME
FROM HACKERS H
JOIN SUBMISSIONS S ON H.HACKER_ID = S.HACKER_ID
WHERE S.SCORE = (SELECT D.SCORE FROM DIFFICULTY D WHERE D.DIFFICULTY_LEVEL = (SELECT C.DIFFICULTY_LEVEL FROM CHALLENGES C WHERE C.CHALLENGE_ID = S.CHALLENGE_ID)  )
GROUP BY H.HACKER_ID,H.NAME
HAVING COUNT(H.HACKER_ID)>1
ORDER BY COUNT(H.HACKER_ID) DESC, H.HACKER_ID ASC;
